app:
    resource: "@AppBundle/Controller/"
    type:     annotation

index:
    pattern:  /
    defaults: { _controller: AlterdBundle:CharacterSheet:index }

list_sheet:
    pattern:  /sheet/list
    defaults: { _controller: AlterdBundle:CharacterSheet:fetchAll }

update_sheet:
    pattern:  /sheet/update
    defaults: { _controller: AlterdBundle:CharacterSheet:update }

generate_sheet:
    pattern:  /sheet/generate
    defaults: { _controller: AlterdBundle:CharacterSheet:generate }

view_sheet:
    pattern:  /sheet/view
    defaults: { _controller: AlterdBundle:CharacterSheet:view }
