<?php

namespace Proxies\__CG__\Alterd\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CharacterSheet extends \Alterd\Entity\CharacterSheet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'id', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'uid', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterName', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterLevel', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterRace', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterSkills', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterAbilities', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterStatPoints', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterSkillPoints', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterHp', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterEn', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterStr', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterAgi', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterSpd', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterWp', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterExp', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterMoney', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterInventory', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterInfo');
        }

        return array('__isInitialized__', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'id', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'uid', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterName', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterLevel', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterRace', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterSkills', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterAbilities', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterStatPoints', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterSkillPoints', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterHp', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterEn', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterStr', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterAgi', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterSpd', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterWp', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterExp', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterMoney', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterInventory', '' . "\0" . 'Alterd\\Entity\\CharacterSheet' . "\0" . 'characterInfo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CharacterSheet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterName($characterName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterName', array($characterName));

        return parent::setCharacterName($characterName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterName', array());

        return parent::getCharacterName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterHp($characterHp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterHp', array($characterHp));

        return parent::setCharacterHp($characterHp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterHp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterHp', array());

        return parent::getCharacterHp();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterEn($characterEn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterEn', array($characterEn));

        return parent::setCharacterEn($characterEn);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterEn', array());

        return parent::getCharacterEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterStr($characterStr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterStr', array($characterStr));

        return parent::setCharacterStr($characterStr);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterStr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterStr', array());

        return parent::getCharacterStr();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterAgi($characterAgi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterAgi', array($characterAgi));

        return parent::setCharacterAgi($characterAgi);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterAgi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterAgi', array());

        return parent::getCharacterAgi();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterSpd($characterSpd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterSpd', array($characterSpd));

        return parent::setCharacterSpd($characterSpd);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterSpd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterSpd', array());

        return parent::getCharacterSpd();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterWp($characterWp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterWp', array($characterWp));

        return parent::setCharacterWp($characterWp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterWp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterWp', array());

        return parent::getCharacterWp();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterMoney($characterMoney)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterMoney', array($characterMoney));

        return parent::setCharacterMoney($characterMoney);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterMoney()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterMoney', array());

        return parent::getCharacterMoney();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterInventory($characterInventory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterInventory', array($characterInventory));

        return parent::setCharacterInventory($characterInventory);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterInventory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterInventory', array());

        return parent::getCharacterInventory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterInfo($characterInfo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterInfo', array($characterInfo));

        return parent::setCharacterInfo($characterInfo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterInfo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterInfo', array());

        return parent::getCharacterInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function getFields()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFields', array());

        return parent::getFields();
    }

    /**
     * {@inheritDoc}
     */
    public function setUid($uid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUid', array($uid));

        return parent::setUid($uid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUid', array());

        return parent::getUid();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterRace($characterRace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterRace', array($characterRace));

        return parent::setCharacterRace($characterRace);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterRace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterRace', array());

        return parent::getCharacterRace();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterSkills($characterSkills)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterSkills', array($characterSkills));

        return parent::setCharacterSkills($characterSkills);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterSkills()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterSkills', array());

        return parent::getCharacterSkills();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterAbilities($characterAbilities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterAbilities', array($characterAbilities));

        return parent::setCharacterAbilities($characterAbilities);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterAbilities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterAbilities', array());

        return parent::getCharacterAbilities();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterStatPoints($characterStatPoints)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterStatPoints', array($characterStatPoints));

        return parent::setCharacterStatPoints($characterStatPoints);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterStatPoints()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterStatPoints', array());

        return parent::getCharacterStatPoints();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterSkillPoints($characterSkillPoints)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterSkillPoints', array($characterSkillPoints));

        return parent::setCharacterSkillPoints($characterSkillPoints);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterSkillPoints()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterSkillPoints', array());

        return parent::getCharacterSkillPoints();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterLevel($characterLevel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterLevel', array($characterLevel));

        return parent::setCharacterLevel($characterLevel);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterLevel', array());

        return parent::getCharacterLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacterExp($characterExp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacterExp', array($characterExp));

        return parent::setCharacterExp($characterExp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacterExp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacterExp', array());

        return parent::getCharacterExp();
    }

}
